language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack: teamcarnell:zhTADgjsb7yJ5RPEd7LPNFwI
  email:
  - carnell28@gmail.com
  on_success: always
  on_failure: always
before_install:
  - sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
  - sudo chmod +x /usr/local/bin/ecs-cli
env:
  global:
  - secure: da8h8K0dKEeVrk+3zO8r9GEv6LqK+23QKZBshsQjyhsu2AT9O6/6EWGbS5mGqTnPPJLqCsEkSEOEUG7BlgCV0gQM7TkvMKGK0DgIJ4usydj2LHNuVMi95BebDUIjUZu0JZmTtjqD92PCUUJ8eRO6765l1gmaU8x9MEdaWWkBHlA96cuJuJLNY8/7el56nj+gofGXsfQUcPMc70It7nArerBCSeQLlT5c69HrMx8znT9cqa0gbjzsoCBs/0VpDE7HqnuQDafoDhQZGoOYf3W2Ubk75mt7F+V0w40HPeJXZFVUZvoihr6yfArypk6S4wZYm19IEi8coZfHosjX1k6IOiQYvXEImyxjyn5VzxEcf5JxRQA1QWjCeNUk1alGKVJYl5cKxeIir2HzHwSQc+4NJIcnL62BiwKJjHUHGBfrujMhl1euhDDv8QWZIFmLm3nIjNeuJJPUh9UL8+xH1wdMe75+ObHtQLfwsDJuzs5/zmErZ3RIl7JJAYTy9QXE8S3sbPs+Bgf7NpUu9FWenNXddz176raVIDXsPaayQ+Y5GX+X/zQz+5Xl0rbTdL7pUst2xSkKEogawLq9zHab021PmwR5IJ+GJG5TTH5zvpHQDbzT//PfCC2HWnzqbcNVdYuH2L9AH6JVMitywdZbFKhyWj+w+IQpS4ddefHX7UoYyoY=
  - secure: QB0IkG1MLj0EyInuU1LJCbIzsB6vrcOmNHF0JZbt4BGi+zN3RLvx/Oxgr1TdkMvsXJAYfhRI4spULsoNjwK9mfgbOPknL281h7MwF1WsjQmIZEgNtSG3GFsPPbTIATfTcd7af+pqM8dDNVD+e5xup1lVoEqt9N/3/LBwQn5W96WzydzLdp6FWGH69/72ZbJUx2L9YigvDoSCc0SOsdOIwtit58vLJ4KLsS3rE2U6TXxs5yuTllgbV4LObSbhZDFrrrZLEVHQWubLK2R1NJjbz5uJA3cjQHx9J5qWbu2l9VgLe2Kv5r+WvJ5TzWQEdCxK9irYPaaXJMqivBoyjAVpxwj1SYn2Zslutq7xhEhx8y0Ai0XQ1/fUPMXOCXrTV0v9tov782uAeCkt4ADPcpcJBOekaafNB85jBVWSfHtXb5mg3QO4bj6dqf8r+3q0IorjxXdYtg0w6bF6N7XmWRPRgy8dDwI4w0eOmLVoGRTAQ5xeUJn9eMsItfEkTUzTY5jJF2fW0T9ymyJDKvPzNuWT79fBQWbf0EtwCjx7mHMX/WtaXjPhmvn9SzOo6B9sL5O3onlaGNhZ3u51E7QW5yLOIr1SaVaDrQ1dBODUBL17TeQzwnWFdcIshRVMwb5aQs0AJxrcrs6ptQts6MIZcwJWAyjEj5r9GRfhThoHHKNy3QQ=
  matrix:
  - TMX_DOCKER_IMAGE=johncarnell/tmx-simple-service:chapter1
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $TMX_DOCKER_IMAGE
- ecs-cli --version
