apiVersion: v1
kind: Service
metadata:
  name: greeting
  labels:
    name: greeting
spec:
  selector:
    app: greeting
  ports:
  - name: http
    protocol: TCP
    port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: name
  labels:
    name: name
spec:
  selector:
    app: name
  ports:
  - name: http
    protocol: TCP
    port: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeting
  labels:
    name: greeting
spec:
  replicas: 
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: arungupta/greeting
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /resources/greeting
            port: 8081
          initialDelaySeconds: 50
          periodSeconds: 5
        env:
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: xray-service.default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: name
  labels:
    name: name
spec:
  replicas: 
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
      - name: name
        image: arungupta/name
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /resources/names/1
            port: 8082
          initialDelaySeconds: 50
          periodSeconds: 5
        env:
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: xray-service.default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  replicas: 
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: arungupta/webapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: NAME_SERVICE_HOST
          value: name
        - name: NAME_SERVICE_PORT
          value: "8082"
        - name: NAME_SERVICE_PATH
          value: /resources/names
        - name: GREETING_SERVICE_HOST
          value: greeting
        - name: GREETING_SERVICE_PORT
          value: "8081"
        - name: GREETING_SERVICE_PATH
          value: /resources/greeting
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: xray-service.default
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
